<div class="cube" id="c1">
    <div class="catalog-product-price">
        <h6>$399,99</h6>
    </div>
    
    <img src="assets/image.png" class="product-image">
    
    <div class="catalog-product-description">
        <h4>Tenis tal</h4>
    </div>
</div>
<div class="cube" id="c2">
    <div class="catalog-product-price">
        <h6>$399,99</h6>
    </div>
    
    <img src="assets/image.png" class="product-image">
    
    <div class="catalog-product-description">
        <h4>Tenis tal</h4>
    </div>
</div>
<div class="cube" id="c3">
    <div class="catalog-product-price">
        <h6>$399,99</h6>
    </div>
    
    <img src="assets/image.png" class="product-image">
    
    <div class="catalog-product-description">
        <h4>Tenis tal</h4>
    </div>
</div>
<div class="cube" id="c4">
    <div class="catalog-catalog-product-price">
        <h6>$399,99</h6>
    </div>
    
    <img src="assets/image.png" class="product-image">
    
    <div class="catalog-catalog-product-description">
        <h4>Tenis tal</h4>
    </div>
</div>